


CREATE PROCEDURE	[lst].[usp_lstAllClientCCN]
					(@ConnectionString NVARCHAR(MAX))

AS

BEGIN
				--DECLARE @ConnectionString NVARCHAR(MAX) = 'ACDW_CLMS_AET_TX_COM.lst.LIST_ICD10CM'
				DECLARE	@SqlString NVARCHAR(MAX)
				

			-----Step 4
--Drop all Targets A
--Creates all Targets B
--Insert into all Target C

--A Drop all Targets
	SET @SqlString = N'DROP TABLE ' +  @ConnectionString 
	EXECUTE sp_executesql @SqlString
		--PRINT @SqlString
 
--B Create all Targets
  
--Create Triggers 
	SET @SqlString = 
	N'CREATE TABLE ' + @ConnectionString + '(' +
	'[CreatedDate]					DATETIME DEFAULT GETDATE()'+
	',[CreatedBy]					VARCHAR(20) DEFAULT SUSER_SNAME()'+
	',[LastUpdated]					DATETIME DEFAULT GETDATE()'+
	',[LastUpdatedBy]				VARCHAR(20) DEFAULT SUSER_SNAME()'+
	',[SrcFileName]					VARCHAR(50)'+
	',[ACTIVE]						CHAR(1) '+
	',[EffectiveDate]				DATE NOT NULL'+
	',[ExpirationDate]				DATE NOT NULL'+
	',lstCNNKey INT IDENTITY (1,1)	PRIMARY KEY'+
	',PRVDR_CTGRY_SBTYP_CD			VARCHAR(10) NULL'+
	',PRVDR_CTGRY_CD				VARCHAR(10) NULL'+
	',CHOW_CNT						INT NULL'+
	',CHOW_DT						DATE NULL'+
	',CITY_NAME						VARCHAR(50) NULL'+
	',ACPTBL_POC_SW					VARCHAR(50) NULL'+
	',CMPLNC_STUS_CD				VARCHAR(10) NULL'+
	',SSA_CNTY_CD					VARCHAR(10) NULL'+
	',CROSS_REF_PROVIDER_NUMBER		VARCHAR(20) NULL'+
	',CRTFCTN_DT					DATE'+
	',ELGBLTY_SW					VARCHAR(20) NULL'+
	',FAC_NAME						VARCHAR(100) NULL'+
	',INTRMDRY_CARR_CD				VARCHAR(10) NULL'+
	',MDCD_VNDR_NUM					VARCHAR(10) NULL'+
	',ORGNL_PRTCPTN_DT				DATE'+
	',CHOW_PRIOR_DT					DATE'+
	',INTRMDRY_CARR_PRIOR_CD		VARCHAR(10)	'+
	',PRVDR_NUM						VARCHAR(10)	'+
	',RGN_CD						VARCHAR(10)	'+
	',SKLTN_REC_SW					VARCHAR(10)	'+
	',STATE_CD						VARCHAR(10)	'+
	',SSA_STATE_CD					VARCHAR(10)	'+
	',STATE_RGN_CD					VARCHAR(10)	'+
	',ST_ADR						VARCHAR(50)	'+
	',PHNE_NUM						VARCHAR(10)	'+
	',PGM_TRMNTN_CD					VARCHAR(10)	'+
	',TRMNTN_EXPRTN_DT				DATE NULL	'+
	',CRTFCTN_ACTN_TYPE_CD			VARCHAR(10)	'+
	',GNRL_CNTL_TYPE_CD				VARCHAR(10)	'+
	',ZIP_CD						VARCHAR(10)	'+
	',FIPS_STATE_CD					VARCHAR(10)	'+
	',FIPS_CNTY_CD					VARCHAR(10)	'+
	',CBSA_URBN_RRL_IND				VARCHAR(10)	'+
	',CBSA_CD						VARCHAR(10)	'+
	',ACRDTN_EFCTV_DT				DATE'+
	',ACRDTN_EXPRTN_DT				DATE'+
	',ACRDTN_TYPE_CD				VARCHAR(10)'+
	',TOT_AFLTD_AMBLNC_SRVC_CNT		INT	'+
	',TOT_AFLTD_ASC_CNT				INT	'+
	',TOT_COLCTD_HOSP_CNT			INT	'+
	',TOT_AFLTD_ESRD_CNT			INT	'+
	',TOT_AFLTD_FQHC_CNT			INT	'+
	',TOT_AFLTD_HHA_CNT				INT	'+
	',TOT_AFLTD_HOSPC_CNT			INT	'+
	',TOT_AFLTD_OPO_CNT				INT	'+
	',TOT_AFLTD_PRTF_CNT			INT	'+
	',TOT_AFLTD_RHC_CNT				INT	'+
	',TOT_AFLTD_SNF_CNT				INT	'+
	',AFLTD_PRVDR_CNT				INT	'+
	',RSDNT_PGM_ALPTHC_SW			VARCHAR(10)'+
	',RSDNT_PGM_DNTL_SW				VARCHAR(10)'+
	',RSDNT_PGM_OSTPTHC_SW			VARCHAR(10)'+
	',RSDNT_PGM_OTHR_SW				VARCHAR(10)'+
	',RSDNT_PGM_PDTRC_SW			VARCHAR(10)'+
	',LAB_SRVC_CD					VARCHAR(10)'+
	',PHRMCY_SRVC_CD				VARCHAR(10)'+
	',RDLGY_SRVC_CD					VARCHAR(10)'+
	',ASC_BGN_SRVC_DT				Date'+
	',FREESTNDNG_ASC_SW				VARCHAR(10)'+
	',OVRRD_BED_CNT_SW				VARCHAR(10)'+
	',CRTFD_BED_CNT					INT'+
	',ICFIID_BED_CNT				INT'+
	',MDCD_NF_BED_CNT				INT'+
	',MDCR_SNF_BED_CNT				INT'+
	',MDCR_MDCD_SNF_BED_CNT			INT'+
	',AIDS_BED_CNT					INT'+
	',ALZHMR_BED_CNT				INT'+
	',DLYS_BED_CNT					INT'+
	',DSBL_CHLDRN_BED_CNT			INT'+
	',HEAD_TRMA_BED_CNT				INT'+
	',HOSPC_BED_CNT					INT'+
	',HNTGTN_DEASE_BED_CNT			INT'+
	',REHAB_BED_CNT					INT'+
	',VNTLTR_BED_CNT				INT'+
	',BED_CNT						INT'+
	',BRNCH_CNT						INT'+
	',BRNCH_OPRTN_SW				VARCHAR(10)'+
	',CAH_PSYCH_DPU_SW				VARCHAR(10)'+
	',CAH_REHAB_DPU_SW				VARCHAR(10)'+
	',CAH_SB_SW						VARCHAR(10)'+
	',CRDC_CTHRTZTN_PRCDR_ROOMS_CNT	INT'+
	',GNRL_FAC_TYPE_CD				VARCHAR(10)'+
	',CHOW_SW						VARCHAR(10)'+
	',CLIA_ID_NUMBER_1				VARCHAR(20)'+
	',CLIA_ID_NUMBER_2				VARCHAR(20)'+
	',CLIA_ID_NUMBER_3				VARCHAR(20)'+
	',CLIA_ID_NUMBER_4				VARCHAR(20)'+
	',CLIA_ID_NUMBER_5				VARCHAR(20)'+
	',COLCTN_STUS_SW				VARCHAR(10)'+
	',RN_24_HR_WVR_SW				VARCHAR(10)'+
	',RN_7_DAY_WVR_SW				VARCHAR(10)'+
	',BED_PER_ROOM_WVR_SW			VARCHAR(20)'+
	',LSC_WVR_SW					VARCHAR(20)'+
	',ROOM_SIZE_WVR_SW				VARCHAR(20)'+
	',ENDSCPY_PRCDR_ROOMS_CNT		INT'+
	',ESRD_NTWRK_NUM				VARCHAR(20)'+
	',EXPRMT_RSRCH_CNDCTD_SW		VARCHAR(20)'+
	',FAX_PHNE_NUM					VARCHAR(20)'+
	',FY_END_MO_DAY_CD				VARCHAR(10)'+
	',FQHC_APPROVED_RHC_PROVIDER_NUM VARCHAR(20)'+
	',FED_FUNDD_FQHC_SW				VARCHAR(20)'+
	',HHA_QLFYD_OPT_SPCH_SW			VARCHAR(20)'+
	',HH_AIDE_TRNG_PGM_CD			VARCHAR(10)'+
	',HOME_TRNG_SPRT_ONLY_SRVC_SW	VARCHAR(20)'+
	',MDCR_HOSPC_SW					VARCHAR(20)'+
	',HOSP_BSD_SW					VARCHAR(20)'+
	',INCNTR_NCTRNL_SRVC_SW			VARCHAR(20)'+
	',LTC_CROSS_REF_PROVIDER_NUMBER	VARCHAR(20)'+
	',MDCL_SCHL_AFLTN_CD				VARCHAR(10)'+
	',MEDICARE_HOSPICE_PROVIDER_NUM	VARCHAR(20)'+
	',MDCD_MDCR_PRTCPTG_PRVDR_SW		VARCHAR(20)'+
	',MEDICARE_MEDICAID_PRVDR_NUMBER	VARCHAR(20)'+
	',MLT_FAC_ORG_NAME				VARCHAR(20)'+
	',MLT_OWND_FAC_ORG_SW			VARCHAR(20)'+
	',NCRY_PRVDR_DSGNTD_DT			DATE'+
	',NCRY_PRVDR_DSGNTD_AS_SW		VARCHAR(20)'+
	',NCRY_PRVDR_LOST_DT				DATE'+
	',MEET_1861_SW					VARCHAR(20)'+
	',NPP_TYPE_CD					VARCHAR(10)'+
	',TOT_OFSITE_CNCR_HOSP_CNT		INT'+
	',TOT_OFSITE_CHLDRN_HOSP_CNT		INT'+
	',TOT_OFSITE_EMER_DEPT_CNT		INT'+
	',TOT_OFSITE_INPTNT_LCTN_CNT		INT'+
	',TOT_OFSITE_LTC_HOSP_CNT		INT'+
	',TOT_OFSITE_OPTHLMC_SRGRY_CNT	INT'+
	',TOT_OFSITE_OTHR_LCTN_CNT		INT'+
	',TOT_OFSITE_PSYCH_HOSP_CNT		INT'+
	',TOT_OFSITE_PSYCH_UNIT_CNT		INT'+
	',TOT_OFSITE_REHAB_HOSP_CNT		INT'+
	',TOT_OFSITE_REHAB_UNIT_CNT		INT'+
	',TOT_OFSITE_URGNT_CARE_CNTR_CNT	INT	'+
	',OFSITE_LCTN_CNT				INT'+
	',OPRTG_ROOM_CNT					INT'+
	',ORGNZ_FMLY_MBR_GRP_SW			VARCHAR(20)'+
	',ORGNZ_RSDNT_GRP_SW				VARCHAR(20)'+
	',PARENT_PROVIDER_NUMBER			VARCHAR(20)'+
	',FQHC_APRVD_RHC_SW				VARCHAR(20)'+
	',MDCR_PRTCPTN_OP_PT_SPCH_SW		VARCHAR(20)'+
	',PGM_PRTCPTN_CD					VARCHAR(10)'+
	',PRVDR_BSD_FAC_SW				VARCHAR(20)'+
	',PRVNC_CD						VARCHAR(10)'+
	',PSYCH_UNIT_BED_CNT				INT'+
	',PSYCH_UNIT_EFCTV_DT			DATE'+
	',PSYCH_UNIT_SW					VARCHAR(20)'+
	',PSYCH_UNIT_TRMNTN_CD			VARCHAR(10)'+
	',PSYCH_UNIT_TRMNTN_DT			DATE'+
	',REHAB_UNIT_BED_CNT				INT'+
	',REHAB_UNIT_EFCTV_DT			DATE'+
	',REHAB_UNIT_SW					VARCHAR(20)'+
	',REHAB_UNIT_TRMNTN_CD			VARCHAR(10)'+
	',REHAB_UNIT_TRMNTN_DT			DATE'+
	',RELATED_PROVIDER_NUMBER		VARCHAR(10)'+
	',ACUTE_RNL_DLYS_SRVC_CD			VARCHAR(10)'+
	',PSYCH_SRVC_CD					VARCHAR(10)'+
	',HH_AIDE_SRVC_CD				VARCHAR(10)'+
	',ALCHL_DRUG_SRVC_CD				VARCHAR(10)'+
	',ANSTHSA_SRVC_CD				VARCHAR(10)'+
	',APLNC_EQUIP_SRVC_CD			VARCHAR(10)'+
	',AUDLGY_SRVC_CD					VARCHAR(10)'+
	',BLOOD_SRVC_OFSITE_RSDNT_SW		VARCHAR(10)'+
	',BLOOD_SRVC_ONST_NRSDNT_SW		VARCHAR(10)	'+
	',BLOOD_SRVC_ONST_RSDNT_SW		VARCHAR(10)'+
	',BURN_CARE_UNIT_SRVC_CD			VARCHAR(10)'+
	',CRDC_CTHRTZTN_LAB_SRVC_CD		VARCHAR(10)'+
	',OPEN_HRT_SRGRY_SRVC_CD			VARCHAR(10)'+
	',CARF_IP_REHAB_SRVC_CD			VARCHAR(10)'+
	',CHMTHRPY_SRVC_CD				VARCHAR(10)'+
	',CHRPRCTIC_SRVC_CD				VARCHAR(10)'+
	',CL_SRVC_OFSITE_RSDNT_SW		VARCHAR(20)'+
	',CL_SRVC_ONST_NRSDNT_SW			VARCHAR(20)'+
	',CL_SRVC_ONST_RSDNT_SW			VARCHAR(20)'+
	',CL_SRVC_CD						VARCHAR(10)'+
	',CRNRY_CARE_UNIT_SRVC_CD		VARCHAR(10)'+
	',CNSLNG_SRVC_CD					VARCHAR(10)'+
	',CT_SCAN_SRVC_CD				VARCHAR(10)'+
	',DNTL_SRVC_CD					VARCHAR(10)'+
	',DNTL_SRVC_OFSITE_RSDNT_SW		VARCHAR(20)'+
	',DNTL_SRVC_ONST_NRSDNT_SW		VARCHAR(20)'+
	',DNTL_SRVC_ONST_RSDNT_SW		VARCHAR(20)'+
	',SHCK_TRMA_SRVC_CD				VARCHAR(10)'+
	',DGNSTC_RDLGY_SRVC_CD			VARCHAR(10)'+
	',DTRY_SRVC_CD					VARCHAR(10)'+
	',DTRY_OFSITE_RSDNT_SW			VARCHAR(20)'+
	',DTRY_ONST_NRSDNT_SW			VARCHAR(20)'+
	',DTRY_ONST_RSDNT_SW				VARCHAR(20)'+
	',DCTD_ER_SRVC_CD				VARCHAR(10)'+
	',EMER_PSYCH_SRVC_CD				VARCHAR(10)'+
	',XTRCRPRL_SHCK_LTHTRPTR_SRVC_CD	VARCHAR(10)'+
	',FRNSC_PSYCH_SRVC_CD			VARCHAR(10)'+
	',GRTRC_PSYCH_SRVC_CD			VARCHAR(10)'+
	',GRNTLGCL_SPCLTY_SRVC_CD		VARCHAR(10)'+
	',SP_HOME_TRNG_SPRT_HD_SW		VARCHAR(20)'+
	',HMDLYS_SRVC_SW					VARCHAR(20)'+
	',HMMKR_SRVC_CD					VARCHAR(10)'+
	',HSEKPNG_SRVC_OFSITE_RSDNT_SW	VARCHAR(20)'+
	',HSEKPNG_SRVC_ONST_NRSDNT_SW	VARCHAR(20)'+
	',HSEKPNG_SRVC_ONST_RSDNT_SW		VARCHAR(20)'+
	',IP_SRGCL_SRVC_CD				VARCHAR(10)'+
	',INTRN_RSDNT_SRVC_CD			VARCHAR(10)'+
	',MDCL_SCL_SRVC_CD				VARCHAR(10)'+
	',MDCL_SUPLY_SRVC_CD				VARCHAR(10)'+
	',ICU_SRVC_CD					VARCHAR(10)'+
	',MDCR_TRNSPLNT_CNTR_SRVC_CD		VARCHAR(10)'+
	',MENTL_HLTH_OFSITE_RSDNT_SW		VARCHAR(20)'+
	',MENTL_HLTH_ONST_NRSDNT_SW		VARCHAR(20)'+
	',MENTL_HLTH_ONST_RSDNT_SW		VARCHAR(10)'+
	',MGNTC_RSNC_IMG_SRVC_CD			VARCHAR(10)'+
	',NEONTL_ICU_SRVC_CD				VARCHAR(10)'+
	',NEONTL_NRSRY_SRVC_CD			VARCHAR(10)'+
	',NRSRGCL_SRVC_CD				VARCHAR(10)'+
	',ORGN_TRNSPLNT_SRVC_CD			VARCHAR(10)'+
	',NUCLR_MDCN_SRVC_CD				VARCHAR(10)'+
	',NRSNG_SRVC_EMPLEE_SW			VARCHAR(20)'+
	',NRSNG_SRVC_CNTRCTR_SW			VARCHAR(20)'+
	',NRSNG_SRVC_ARNGMT_SW			VARCHAR(20)'+
	',NRSNG_SRVC_CD					VARCHAR(10)'+
	',NRSNG_SRVC_OFSITE_RSDNT_SW		VARCHAR(20)'+
	',NRSNG_SRVC_ONST_NRSDNT_SW		VARCHAR(20)'+
	',NRSNG_SRVC_ONST_RSDNT_SW		VARCHAR(20)'+
	',NTRTNL_GDNC_SRVC_CD			VARCHAR(10)'+
	',OB_SRVC_CD						VARCHAR(10)'+
	',OPTHLMC_SRGY_SRVC_CD			VARCHAR(10)'+
	',OPTMTRC_SRVC_CD				VARCHAR(10)'+
	',OPRTG_ROOM_SRVC_CD				VARCHAR(10)'+
	',ORTHPDC_SRGY_SRVC_CD			VARCHAR(10)'+
	',ORTHTC_PRSTHTC_EMPLEE_SW		VARCHAR(20)'+
	',ORTHTC_PRSTHTC_CNTRCTR_SW		VARCHAR(20)'+
	',ORTHTC_PRSTHTC_ARNGMT_SW		VARCHAR(20)'+
	',OT_EMPLEE_SW					VARCHAR(20)'+
	',OT_CNTRCTR_SW					VARCHAR(20)'+
	',OT_ARNGMT_SW					VARCHAR(20)'+
	',OT_SRVC_CD						VARCHAR(10)'+
	',OT_SRVC_OFSITE_RSDNT_SW		VARCHAR(20)'+
	',OT_SRVC_ONST_NRSDNT_SW			VARCHAR(20)'+
	',OT_SRVC_ONST_RSDNT_SW			VARCHAR(20)'+
	',OTHR_SRVC_CD					VARCHAR(10)'+
	',OP_SRVC_CD						VARCHAR(10)'+
	',OP_PSYCH_SRVC_CD				VARCHAR(10)'+
	',OP_REHAB_SRVC_CD				VARCHAR(10)'+
	',OP_SRGRY_UNIT_SRVC_CD			VARCHAR(10)'+
	',PED_SRVC_CD					VARCHAR(10)'+
	',PED_ICU_SRVC_CD				VARCHAR(10)'+
	',SP_HOME_TRNG_SPRT_PD_SW		VARCHAR(20)'+
	',PRTNL_DLYS_SRVC_SW				VARCHAR(20)'+
	',PET_SCAN_SRVC_CD				VARCHAR(20)'+
	',PHRMCY_SRVC_OFSITE_RSDNT_SW	VARCHAR(20)'+
	',PHRMCY_SRVC_ONST_NRSDNT_SW		VARCHAR(20)'+
	',PHRMCY_SRVC_ONST_RSDNT_SW		VARCHAR(20)'+
	',PHYSN_EMPLEE_SW				VARCHAR(20)'+
	',PHYSN_CNTRCTR_SW				VARCHAR(20)'+
	',PHYSN_ARNGMT_SW				VARCHAR(20)'+
	',PHYSN_SRVC_CD					VARCHAR(20)'+
	',PHYSN_EXT_SRVC_OFSITE_RSDNT_SW	VARCHAR(20)'+
	',PHYSN_EXT_SRVC_ONST_NRSDNT_SW	VARCHAR(20)'+
	',PHYSN_EXT_SRVC_ONST_RSDNT_SW	VARCHAR(20)'+
	',PHYSN_SRVC_OFSITE_RSDNT_SW		VARCHAR(20)'+
	',PHYSN_SRVC_ONST_NRSDNT_SW		VARCHAR(20)'+
	',PHYSN_SRVC_ONST_RSDNT_SW		VARCHAR(20)'+
	',PDTRY_SRVC_OFSITE_RSDNT_SW		VARCHAR(20)'+
	',PDTRY_SRVC_ONST_NRSDNT_SW		VARCHAR(20)'+
	',PDTRY_SRVC_ONST_RSDNT_SW		VARCHAR(20)'+
	',PSTOPRTV_RCVRY_SRVC_CD			VARCHAR(10)'+
	',CHLD_ADLSCNT_PSYCH_SRVC_CD		VARCHAR(10)'+
	',PSYCHLGCL_EMPLEE_SW			VARCHAR(20)'+
	',PSYCHLGCL_CNTRCTR_SW			VARCHAR(20)'+
	',PSYCHLGCL_ARNGMT_SW			VARCHAR(20)'+
	',PT_EMPLEE_SW					VARCHAR(20)'+
	',PT_CNTRCTR_SW					VARCHAR(20)'+
	',PT_ARNGMT_SW					VARCHAR(20)'+
	',PT_SRVC_CD						VARCHAR(10)'+
	',PT_OFSITE_RSDNT_SW				VARCHAR(20)'+
	',PT_ONST_NRSDNT_SW				VARCHAR(20)'+
	',PT_ONST_RSDNT_SW				VARCHAR(20)'+
	',RCNSTRCTN_SRGY_SRVC_CD			VARCHAR(10)'+
	',RSPRTRY_CARE_EMPLEE_SW			VARCHAR(20)'+
	',RSPRTRY_CARE_CNTRCTR_SW		VARCHAR(20)'+
	',RSPRTRY_CARE_ARNGMT_SW			VARCHAR(20)'+
	',RSPRTRY_CARE_SRVC_CD			VARCHAR(10)'+
	',SHRT_TERM_IP_SRVC_CD			VARCHAR(10)'+
	',SCL_EMPLEE_SW					VARCHAR(20)'+
	',SCL_CNTRCTR_SW					VARCHAR(20)'+
	',SCL_ARNGMT_SW					VARCHAR(20)'+
	',SCL_SRVC_CD					VARCHAR(10)'+
	',SCL_WORK_SRVC_OFSITE_RSDNT_SW	VARCHAR(20)'+
	',SCL_WORK_SRVC_ONST_NRSDNT_SW	VARCHAR(20)'+
	',SCL_WORK_SRVC_ONST_RSDNT_SW	VARCHAR(20)'+
	',SPCH_PTHLGY_EMPLEE_SW			VARCHAR(20)'+
	',SPCH_PTHLGY_CNTRCTR_SW			VARCHAR(20)'+
	',SPCH_PTHLGY_ARNGMT_SW			VARCHAR(20)'+
	',SPCH_PTHLGY_SRVC_CD			VARCHAR(10)'+
	',SPCH_PTHLGY_OFSITE_RSDNT_SW	VARCHAR(20)'+
	',SPCH_PTHLGY_ONST_NRSDNT_SW		VARCHAR(20)'+
	',SPCH_PTHLGY_ONST_RSDNT_SW		VARCHAR(20)'+
	',SPCH_THRPY_SRVC_CD				VARCHAR(10)'+
	',SRGCL_ICU_SRVC_CD				VARCHAR(10)'+
	',ACTVTY_OTHR_OFSITE_RSDNT_SW	VARCHAR(20)'+
	',ACTVTY_OTHR_ONST_NRSDNT_SW		VARCHAR(20)'+
	',ACTVTY_OTHR_ONST_RSDNT_SW		VARCHAR(20)'+
	',SCL_SRVC_OTHR_OFSITE_RSDNT_SW	VARCHAR(20)'+
	',SCL_SRVC_OTHR_ONST_NRSDNT_SW	VARCHAR(20)'+
	',SCL_SRVC_OTHR_ONST_RSDNT_SW	VARCHAR(20)'+
	',ACTVTY_OFSITE_RSDNT_SW			VARCHAR(20)'+
	',ACTVTY_ONST_NRSDNT_SW			VARCHAR(20)'+
	',ACTVTY_ONST_RSDNT_SW			VARCHAR(20)'+
	',THRPTC_RDLGY_SRVC_CD			VARCHAR(10)'+
	',THRPTC_RCRTNL_OFSITE_RSDNT_SW	VARCHAR(20)'+
	',THRPTC_RCRTNL_ONST_NRSDNT_SW	VARCHAR(20)'+
	',THRPTC_RCRTNL_ONST_RSDNT_SW	VARCHAR(20)'+
	',URGNT_CARE_SRVC_CD				VARCHAR(10)'+
	',VCTNL_GDNC_SRVC_CD				VARCHAR(10)'+
	',VCTNL_SRVC_OFSITE_RSDNT_SW		VARCHAR(20)'+
	',VCTNL_SRVC_ONST_NRSDNT_SW		VARCHAR(20)'+
	',VCTNL_SRVC_ONST_RSDNT_SW		VARCHAR(20)'+
	',DGNSTC_XRAY_OFSITE_RSDNT_SW	VARCHAR(20)'+
	',DGNSTC_XRAY_ONST_NRSDNT_SW		VARCHAR(20)'+
	',DGNSTC_XRAY_ONST_RSDNT_SW		VARCHAR(20)'+
	',ACUTE_RESP_CARE_CD				VARCHAR(10)'+
	',OVRRD_STFG_SW					VARCHAR(20)'+
	',PROFNL_ADMIN_CNTRCT_CNT		INT'+
	',PROFNL_ADMIN_FLTM_CNT			INT'+
	',PROFNL_ADMIN_PRTM_CNT			INT'+
	',HH_AIDE_EMPLEE_CNT				INT'+
	',HH_AIDE_VLNTR_CNT				INT'+
	',PRSNEL_OTHR_CNT				DECIMAL(30,2)'+
	',NRS_AIDE_CNTRCT_CNT			INT'+
	',NRS_AIDE_FLTM_CNT				INT'+
	',NRS_AIDE_PRTM_CNT				INT'+
	',CNSLR_EMPLEE_CNT				INT'+
	',CNSLR_VLNTR_CNT				INT'+
	',CRNA_CNT						DECIMAL(30,2)'+
	',DNTST_CNTRCT_CNT				INT'+
	',DNTST_FLTM_CNT					INT'+
	',DNTST_PRTM_CNT					INT'+
	',DIETN_CNT						DECIMAL(30,2)'+
	',DIETN_CNTRCT_CNT				INT'+
	',DIETN_FLTM_CNT					INT'+
	',DIETN_PRTM_CNT					INT'+
	',DRCT_CARE_PRSNEL_CNT			INT'+
	',FOOD_SRVC_CNTRCT_CNT			INT'+
	',FOOD_SRVC_FLTM_CNT				INT'+
	',FOOD_SRVC_PRTM_CNT				INT'+
	',HH_AIDE_CNT					INT'+
	',HMMKR_EMPLEE_CNT				INT'+
	',HMMKR_VLNTR_CNT				INT'+
	',HSEKPNG_CNTRCT_CNT				INT'+
	',HSEKPNG_FLTM_CNT				INT'+
	',HSEKPNG_PRTM_CNT				INT'+
	',LAB_TCHNCN_CNT					DECIMAL(30,2)'+
	',LPN_CNT						INT'+
	',LPN_LVN_CNT					DECIMAL(30,2)'+
	',LPN_LVN_CNTRCT_CNT				INT'+
	',LPN_LVN_FLTM_CNT				INT'+
	',LPN_LVN_PRTM_CNT				INT'+
	',LPN_LVN_VLNTR_CNT				INT'+
	',MDCL_DRCTR_CNTRCT_CNT			INT'+
	',MDCL_DRCTR_FLTM_CNT			INT'+
	',MDCL_DRCTR_PRTM_CNT			INT'+
	',MDCL_SCL_WORKR_CNT				DECIMAL(30,2)'+
	',MDCL_SCL_WORKR_VLNTR_CNT		INT'+
	',MDCL_TCHNLGST_CNT				DECIMAL(30,2)'+
	',MDCTN_AIDE_CNTRCT_CNT			INT'+
	',MDCTN_AIDE_FLTM_CNT			INT'+
	',MDCTN_AIDE_PRTM_CNT			INT'+
	',MENTL_HLTH_SRVC_CNTRCT_CNT		INT'+
	',MENTL_HLTH_SRVC_FLTM_CNT		INT'+
	',MENTL_HLTH_SRVC_PRTM_CNT		INT'+
	',NUCLR_MDCN_TCHNCN_CNT			DECIMAL(30,2)'+
	',NAT_CNTRCT_CNT					INT'+
	',NAT_FLTM_CNT					INT'+
	',NAT_PRTM_CNT					INT'+
	',NRS_PRCTNR_CNT					DECIMAL(30,2)'+
	',NRS_ADMINV_CNTRCT_CNT			INT'+
	',NRS_ADMINV_FLTM_CNT			INT'+
	',NRS_ADMINV_PRTM_CNT			INT'+
	',OCPTNL_THRPST_CNT				DECIMAL(30,2)'+
	',OCPTNL_THRPST_CNTRCT_CNT		INT'+
	',OCPTNL_THRPST_FLTM_CNT			INT'+
	',OCPTNL_THRPST_PRTM_CNT			INT'+
	',OT_AIDE_CNTRCT_CNT				INT'+
	',OT_AIDE_FLTM_CNT				INT'+
	',OT_AIDE_PRTM_CNT				INT'+
	',OT_ASTNT_CNTRCT_CNT			INT'+
	',OT_ASTNT_FLTM_CNT				INT'+
	',OT_ASTNT_PRTM_CNT				INT'+
	',VLNTR_OTHR_CNT					INT'+
	',ACTVTY_STF_OTHR_CNTRCT_CNT		INT'+
	',ACTVTY_STF_OTHR_FLTM_CNT		INT'+
	',ACTVTY_STF_OTHR_PRTM_CNT		INT'+
	',PHYSN_OTHR_CNTRCT_CNT			INT'+
	',PHYSN_OTHR_FLTM_CNT			INT'+
	',PHYSN_OTHR_PRTM_CNT			INT'+
	',SCL_SRVC_OTHR_STF_CNTRCT_CNT	INT'+
	',SCL_SRVC_OTHR_STF_FLTM_CNT		INT'+
	',SCL_SRVC_OTHR_STF_PRTM_CNT		INT'+
	',STF_OTHR_CNTRCT_CNT			INT'+
	',STF_OTHR_FLTM_CNT				INT'+
	',STF_OTHR_PRTM_CNT				INT'+
	',PHRMCST_CNTRCT_CNT				INT'+
	',PHRMCST_FLTM_CNT				INT'+
	',PHRMCST_PRTM_CNT				INT'+
	',PHYS_THRPST_CNTRCT_CNT			INT'+
	',PHYS_THRPST_FLTM_CNT			INT'+
	',PHYS_THRPST_PRTM_CNT			INT'+
	',PHYSN_CNT						DECIMAL(30,2)'+
	',PHYSN_VLNTR_CNT				INT'+
	',PHYSN_ASTNT_CNT				DECIMAL(30,2)'+
	',PHYSN_EXT_CNTRCT_CNT			INT'+
	',PHYSN_EXT_FLTM_CNT				INT'+
	',PHYSN_EXT_PRTM_CNT				INT'+
	',RSDNT_PHYSN_CNT				DECIMAL(30,2)'+
	',PDTRST_CNTRCT_CNT				INT'+
	',PDTRST_FLTM_CNT				INT'+
	',PDTRST_PRTM_CNT				INT'+
	',PSYCHLGST_CNT					DECIMAL(30,2)'+
	',PHYS_THRPST_STF_CNT			INT'+
	',PHYS_THRPST_CNT				DECIMAL(30,2)'+
	',PHYS_THRPST_ARNGMT_CNT			INT'+
	',PT_AIDE_CNTRCT_CNT				INT'+
	',PT_AIDE_FLTM_CNT				INT'+
	',PT_AIDE_PRTM_CNT				INT'+
	',PT_ASTNT_CNTRCT_CNT			INT'+
	',PT_ASTNT_FLTM_CNT				INT'+
	',PT_ASTNT_PRTM_CNT				INT'+
	',ACTVTY_PROFNL_CNTRCT_CNT		INT'+
	',ACTVTY_PROFNL_FLTM_CNT			INT'+
	',ACTVTY_PROFNL_PRTM_CNT			INT'+
	',RDLGY_TCHNCN_CNT				DECIMAL (30,2)'+
	',REG_PHRMCST_CNT				DECIMAL (30,2)'+
	',INHLTN_THRPST_CNT				DECIMAL (30,2)'+
	',RN_CNT							DECIMAL (30,2)'+
	',RN_CNTRCT_CNT					INT'+
	',RN_FLTM_CNT					INT'+
	',RN_PRTM_CNT					INT'+
	',RN_VLNTR_CNT					INT'+
	',RN_DRCTR_CNTRCT_CNT			INT'+
	',RN_DRCTR_FLTM_CNT				INT'+
	',RN_DRCTR_PRTM_CNT				INT'+
	',SCL_WORKR_CNT					INT'+
	',SCL_WORKR_CNTRCT_CNT			INT'+
	',SCL_WORKR_FLTM_CNT				INT'+
	',SCL_WORKR_PRTM_CNT				INT'+
	',SPCH_PTHLGST_ARNGMT_CNT		INT'+
	',SPCH_PTHLGST_CNTRCT_CNT		INT'+
	',SPCH_PTHLGST_FLTM_CNT			INT'+
	',SPCH_PTHLGST_PRTM_CNT			INT'+
	',SPCH_PTHLGST_CNT				INT'+
	',SPCH_PTHLGST_AUDLGST_CNT		DECIMAL (30,2)'+
	',TCHNCL_STF_NUM					VARCHAR(20)'+
	',TCHNCN_CNT						INT'+
	',THRPTC_RCRTNL_CNTRCT_CNT		INT'+
	',THRPTC_RCRTNL_FLTM_CNT			INT'+
	',THRPTC_RCRTNL_PRTM_CNT			INT'+
	',EMPLEE_CNT						INT'+
	',VLNTR_CNT						INT'+
	',SBUNIT_CNT						INT'+
	',SBUNIT_SW						VARCHAR(20)'+
	',SBUNIT_OPRTN_SW				VARCHAR(20)'+
	',DNTL_SRGRY_SW					VARCHAR(20)'+
	',OTLRYNGLGY_SRGRY_SW			VARCHAR(20)'+
	',ENDSCPY_SRGRY_SW				VARCHAR(20)'+
	',OB_GYN_SRGRY_SW				VARCHAR(20)'+
	',OPTHMLGY_SRGRY_SW				VARCHAR(20)'+
	',ORTHPDC_SRGRY_SW				VARCHAR(20)'+
	',OTHR_SRGRY_SW					VARCHAR(20)'+
	',PAIN_SRGRY_SW					VARCHAR(20)'+
	',PLSTC_SRGRY_SW					VARCHAR(20)'+
	',FT_SRGRY_SW					VARCHAR(20)'+
	',SB_SW							VARCHAR(20)'+
	',SB_SIZE_CD						VARCHAR(10)'+
	',TCHNLGST_2_YR_RDLGC_CNT		INT'+
	',TCHNLGST_ASCT_DGR_CNT			INT'+
	',TCHNLGST_BS_BA_DGR_CNT			INT'+
	',DLYS_STN_CNT					INT'+
	')'

	--PRINT @SqlString
	EXECUTE sp_executesql @SqlString


--C Insert into all Target 

SET  @SqlString = 
		'SET IDENTITY_INSERT ' + @ConnectionString + ' ON ' +
		N'INSERT INTO ' + @ConnectionString + '('
		+	'[CreatedDate], [CreatedBy], [LastUpdated], [LastUpdatedBy], [SrcFileName], [ACTIVE], [EffectiveDate], [ExpirationDate], [lstCNNKey], [PRVDR_CTGRY_SBTYP_CD], [PRVDR_CTGRY_CD]
		, [CHOW_CNT], [CHOW_DT], [CITY_NAME], [ACPTBL_POC_SW], [CMPLNC_STUS_CD], [SSA_CNTY_CD], [CROSS_REF_PROVIDER_NUMBER], [CRTFCTN_DT], [ELGBLTY_SW], [FAC_NAME], [INTRMDRY_CARR_CD]
		, [MDCD_VNDR_NUM], [ORGNL_PRTCPTN_DT], [CHOW_PRIOR_DT], [INTRMDRY_CARR_PRIOR_CD], [PRVDR_NUM], [RGN_CD], [SKLTN_REC_SW], [STATE_CD], [SSA_STATE_CD], [STATE_RGN_CD], [ST_ADR], [PHNE_NUM]
		, [PGM_TRMNTN_CD], [TRMNTN_EXPRTN_DT], [CRTFCTN_ACTN_TYPE_CD], [GNRL_CNTL_TYPE_CD], [ZIP_CD], [FIPS_STATE_CD], [FIPS_CNTY_CD], [CBSA_URBN_RRL_IND], [CBSA_CD], [ACRDTN_EFCTV_DT], [ACRDTN_EXPRTN_DT]
		, [ACRDTN_TYPE_CD], [TOT_AFLTD_AMBLNC_SRVC_CNT], [TOT_AFLTD_ASC_CNT], [TOT_COLCTD_HOSP_CNT], [TOT_AFLTD_ESRD_CNT], [TOT_AFLTD_FQHC_CNT], [TOT_AFLTD_HHA_CNT], [TOT_AFLTD_HOSPC_CNT], [TOT_AFLTD_OPO_CNT]
		, [TOT_AFLTD_PRTF_CNT], [TOT_AFLTD_RHC_CNT], [TOT_AFLTD_SNF_CNT], [AFLTD_PRVDR_CNT], [RSDNT_PGM_ALPTHC_SW], [RSDNT_PGM_DNTL_SW], [RSDNT_PGM_OSTPTHC_SW], [RSDNT_PGM_OTHR_SW], [RSDNT_PGM_PDTRC_SW]
		, [LAB_SRVC_CD], [PHRMCY_SRVC_CD], [RDLGY_SRVC_CD], [ASC_BGN_SRVC_DT], [FREESTNDNG_ASC_SW], [OVRRD_BED_CNT_SW], [CRTFD_BED_CNT], [ICFIID_BED_CNT], [MDCD_NF_BED_CNT], [MDCR_SNF_BED_CNT]
		, [MDCR_MDCD_SNF_BED_CNT], [AIDS_BED_CNT], [ALZHMR_BED_CNT], [DLYS_BED_CNT], [DSBL_CHLDRN_BED_CNT], [HEAD_TRMA_BED_CNT], [HOSPC_BED_CNT], [HNTGTN_DEASE_BED_CNT], [REHAB_BED_CNT], [VNTLTR_BED_CNT]
		, [BED_CNT], [BRNCH_CNT], [BRNCH_OPRTN_SW], [CAH_PSYCH_DPU_SW], [CAH_REHAB_DPU_SW], [CAH_SB_SW], [CRDC_CTHRTZTN_PRCDR_ROOMS_CNT], [GNRL_FAC_TYPE_CD], [CHOW_SW], [CLIA_ID_NUMBER_1], [CLIA_ID_NUMBER_2]
		, [CLIA_ID_NUMBER_3], [CLIA_ID_NUMBER_4], [CLIA_ID_NUMBER_5], [COLCTN_STUS_SW], [RN_24_HR_WVR_SW], [RN_7_DAY_WVR_SW], [BED_PER_ROOM_WVR_SW], [LSC_WVR_SW], [ROOM_SIZE_WVR_SW], [ENDSCPY_PRCDR_ROOMS_CNT]
		, [ESRD_NTWRK_NUM], [EXPRMT_RSRCH_CNDCTD_SW], [FAX_PHNE_NUM], [FY_END_MO_DAY_CD], [FQHC_APPROVED_RHC_PROVIDER_NUM], [FED_FUNDD_FQHC_SW], [HHA_QLFYD_OPT_SPCH_SW], [HH_AIDE_TRNG_PGM_CD]
		, [HOME_TRNG_SPRT_ONLY_SRVC_SW], [MDCR_HOSPC_SW], [HOSP_BSD_SW], [INCNTR_NCTRNL_SRVC_SW], [LTC_CROSS_REF_PROVIDER_NUMBER], [MDCL_SCHL_AFLTN_CD], [MEDICARE_HOSPICE_PROVIDER_NUM], [MDCD_MDCR_PRTCPTG_PRVDR_SW]
		, [MEDICARE_MEDICAID_PRVDR_NUMBER], [MLT_FAC_ORG_NAME], [MLT_OWND_FAC_ORG_SW], [NCRY_PRVDR_DSGNTD_DT], [NCRY_PRVDR_DSGNTD_AS_SW], [NCRY_PRVDR_LOST_DT], [MEET_1861_SW], [NPP_TYPE_CD], [TOT_OFSITE_CNCR_HOSP_CNT]
		, [TOT_OFSITE_CHLDRN_HOSP_CNT], [TOT_OFSITE_EMER_DEPT_CNT], [TOT_OFSITE_INPTNT_LCTN_CNT], [TOT_OFSITE_LTC_HOSP_CNT], [TOT_OFSITE_OPTHLMC_SRGRY_CNT], [TOT_OFSITE_OTHR_LCTN_CNT], [TOT_OFSITE_PSYCH_HOSP_CNT]
		, [TOT_OFSITE_PSYCH_UNIT_CNT], [TOT_OFSITE_REHAB_HOSP_CNT], [TOT_OFSITE_REHAB_UNIT_CNT], [TOT_OFSITE_URGNT_CARE_CNTR_CNT], [OFSITE_LCTN_CNT], [OPRTG_ROOM_CNT], [ORGNZ_FMLY_MBR_GRP_SW], [ORGNZ_RSDNT_GRP_SW]
		, [PARENT_PROVIDER_NUMBER], [FQHC_APRVD_RHC_SW], [MDCR_PRTCPTN_OP_PT_SPCH_SW], [PGM_PRTCPTN_CD], [PRVDR_BSD_FAC_SW], [PRVNC_CD], [PSYCH_UNIT_BED_CNT], [PSYCH_UNIT_EFCTV_DT], [PSYCH_UNIT_SW], [PSYCH_UNIT_TRMNTN_CD]
		, [PSYCH_UNIT_TRMNTN_DT], [REHAB_UNIT_BED_CNT], [REHAB_UNIT_EFCTV_DT], [REHAB_UNIT_SW], [REHAB_UNIT_TRMNTN_CD], [REHAB_UNIT_TRMNTN_DT], [RELATED_PROVIDER_NUMBER], [ACUTE_RNL_DLYS_SRVC_CD], [PSYCH_SRVC_CD]
		, [HH_AIDE_SRVC_CD], [ALCHL_DRUG_SRVC_CD], [ANSTHSA_SRVC_CD], [APLNC_EQUIP_SRVC_CD], [AUDLGY_SRVC_CD], [BLOOD_SRVC_OFSITE_RSDNT_SW], [BLOOD_SRVC_ONST_NRSDNT_SW], [BLOOD_SRVC_ONST_RSDNT_SW]
		, [BURN_CARE_UNIT_SRVC_CD], [CRDC_CTHRTZTN_LAB_SRVC_CD], [OPEN_HRT_SRGRY_SRVC_CD], [CARF_IP_REHAB_SRVC_CD], [CHMTHRPY_SRVC_CD], [CHRPRCTIC_SRVC_CD], [CL_SRVC_OFSITE_RSDNT_SW], [CL_SRVC_ONST_NRSDNT_SW]
		, [CL_SRVC_ONST_RSDNT_SW], [CL_SRVC_CD], [CRNRY_CARE_UNIT_SRVC_CD], [CNSLNG_SRVC_CD], [CT_SCAN_SRVC_CD], [DNTL_SRVC_CD], [DNTL_SRVC_OFSITE_RSDNT_SW], [DNTL_SRVC_ONST_NRSDNT_SW], [DNTL_SRVC_ONST_RSDNT_SW]
		, [SHCK_TRMA_SRVC_CD], [DGNSTC_RDLGY_SRVC_CD], [DTRY_SRVC_CD], [DTRY_OFSITE_RSDNT_SW], [DTRY_ONST_NRSDNT_SW], [DTRY_ONST_RSDNT_SW], [DCTD_ER_SRVC_CD], [EMER_PSYCH_SRVC_CD], [XTRCRPRL_SHCK_LTHTRPTR_SRVC_CD]
		, [FRNSC_PSYCH_SRVC_CD], [GRTRC_PSYCH_SRVC_CD], [GRNTLGCL_SPCLTY_SRVC_CD], [SP_HOME_TRNG_SPRT_HD_SW], [HMDLYS_SRVC_SW], [HMMKR_SRVC_CD], [HSEKPNG_SRVC_OFSITE_RSDNT_SW], [HSEKPNG_SRVC_ONST_NRSDNT_SW]
		, [HSEKPNG_SRVC_ONST_RSDNT_SW], [IP_SRGCL_SRVC_CD], [INTRN_RSDNT_SRVC_CD], [MDCL_SCL_SRVC_CD], [MDCL_SUPLY_SRVC_CD], [ICU_SRVC_CD], [MDCR_TRNSPLNT_CNTR_SRVC_CD], [MENTL_HLTH_OFSITE_RSDNT_SW]
		, [MENTL_HLTH_ONST_NRSDNT_SW], [MENTL_HLTH_ONST_RSDNT_SW], [MGNTC_RSNC_IMG_SRVC_CD], [NEONTL_ICU_SRVC_CD], [NEONTL_NRSRY_SRVC_CD], [NRSRGCL_SRVC_CD], [ORGN_TRNSPLNT_SRVC_CD], [NUCLR_MDCN_SRVC_CD]
		, [NRSNG_SRVC_EMPLEE_SW], [NRSNG_SRVC_CNTRCTR_SW], [NRSNG_SRVC_ARNGMT_SW], [NRSNG_SRVC_CD], [NRSNG_SRVC_OFSITE_RSDNT_SW], [NRSNG_SRVC_ONST_NRSDNT_SW], [NRSNG_SRVC_ONST_RSDNT_SW], [NTRTNL_GDNC_SRVC_CD]
		, [OB_SRVC_CD], [OPTHLMC_SRGY_SRVC_CD], [OPTMTRC_SRVC_CD], [OPRTG_ROOM_SRVC_CD], [ORTHPDC_SRGY_SRVC_CD], [ORTHTC_PRSTHTC_EMPLEE_SW], [ORTHTC_PRSTHTC_CNTRCTR_SW], [ORTHTC_PRSTHTC_ARNGMT_SW], [OT_EMPLEE_SW]
		, [OT_CNTRCTR_SW], [OT_ARNGMT_SW], [OT_SRVC_CD], [OT_SRVC_OFSITE_RSDNT_SW], [OT_SRVC_ONST_NRSDNT_SW], [OT_SRVC_ONST_RSDNT_SW], [OTHR_SRVC_CD], [OP_SRVC_CD], [OP_PSYCH_SRVC_CD], [OP_REHAB_SRVC_CD]
		, [OP_SRGRY_UNIT_SRVC_CD], [PED_SRVC_CD], [PED_ICU_SRVC_CD], [SP_HOME_TRNG_SPRT_PD_SW], [PRTNL_DLYS_SRVC_SW], [PET_SCAN_SRVC_CD], [PHRMCY_SRVC_OFSITE_RSDNT_SW], [PHRMCY_SRVC_ONST_NRSDNT_SW]
		, [PHRMCY_SRVC_ONST_RSDNT_SW], [PHYSN_EMPLEE_SW], [PHYSN_CNTRCTR_SW], [PHYSN_ARNGMT_SW], [PHYSN_SRVC_CD], [PHYSN_EXT_SRVC_OFSITE_RSDNT_SW], [PHYSN_EXT_SRVC_ONST_NRSDNT_SW], [PHYSN_EXT_SRVC_ONST_RSDNT_SW]
		, [PHYSN_SRVC_OFSITE_RSDNT_SW], [PHYSN_SRVC_ONST_NRSDNT_SW], [PHYSN_SRVC_ONST_RSDNT_SW], [PDTRY_SRVC_OFSITE_RSDNT_SW], [PDTRY_SRVC_ONST_NRSDNT_SW], [PDTRY_SRVC_ONST_RSDNT_SW], [PSTOPRTV_RCVRY_SRVC_CD]
		, [CHLD_ADLSCNT_PSYCH_SRVC_CD], [PSYCHLGCL_EMPLEE_SW], [PSYCHLGCL_CNTRCTR_SW], [PSYCHLGCL_ARNGMT_SW], [PT_EMPLEE_SW], [PT_CNTRCTR_SW], [PT_ARNGMT_SW], [PT_SRVC_CD], [PT_OFSITE_RSDNT_SW], [PT_ONST_NRSDNT_SW]
		, [PT_ONST_RSDNT_SW], [RCNSTRCTN_SRGY_SRVC_CD], [RSPRTRY_CARE_EMPLEE_SW], [RSPRTRY_CARE_CNTRCTR_SW], [RSPRTRY_CARE_ARNGMT_SW], [RSPRTRY_CARE_SRVC_CD], [SHRT_TERM_IP_SRVC_CD], [SCL_EMPLEE_SW], [SCL_CNTRCTR_SW]
		, [SCL_ARNGMT_SW], [SCL_SRVC_CD], [SCL_WORK_SRVC_OFSITE_RSDNT_SW], [SCL_WORK_SRVC_ONST_NRSDNT_SW], [SCL_WORK_SRVC_ONST_RSDNT_SW], [SPCH_PTHLGY_EMPLEE_SW], [SPCH_PTHLGY_CNTRCTR_SW], [SPCH_PTHLGY_ARNGMT_SW]
		, [SPCH_PTHLGY_SRVC_CD], [SPCH_PTHLGY_OFSITE_RSDNT_SW], [SPCH_PTHLGY_ONST_NRSDNT_SW], [SPCH_PTHLGY_ONST_RSDNT_SW], [SPCH_THRPY_SRVC_CD], [SRGCL_ICU_SRVC_CD], [ACTVTY_OTHR_OFSITE_RSDNT_SW]
		, [ACTVTY_OTHR_ONST_NRSDNT_SW], [ACTVTY_OTHR_ONST_RSDNT_SW], [SCL_SRVC_OTHR_OFSITE_RSDNT_SW], [SCL_SRVC_OTHR_ONST_NRSDNT_SW], [SCL_SRVC_OTHR_ONST_RSDNT_SW], [ACTVTY_OFSITE_RSDNT_SW], [ACTVTY_ONST_NRSDNT_SW]
		, [ACTVTY_ONST_RSDNT_SW], [THRPTC_RDLGY_SRVC_CD], [THRPTC_RCRTNL_OFSITE_RSDNT_SW], [THRPTC_RCRTNL_ONST_NRSDNT_SW], [THRPTC_RCRTNL_ONST_RSDNT_SW], [URGNT_CARE_SRVC_CD], [VCTNL_GDNC_SRVC_CD]
		, [VCTNL_SRVC_OFSITE_RSDNT_SW], [VCTNL_SRVC_ONST_NRSDNT_SW], [VCTNL_SRVC_ONST_RSDNT_SW], [DGNSTC_XRAY_OFSITE_RSDNT_SW], [DGNSTC_XRAY_ONST_NRSDNT_SW], [DGNSTC_XRAY_ONST_RSDNT_SW], [ACUTE_RESP_CARE_CD]
		, [OVRRD_STFG_SW], [PROFNL_ADMIN_CNTRCT_CNT], [PROFNL_ADMIN_FLTM_CNT], [PROFNL_ADMIN_PRTM_CNT], [HH_AIDE_EMPLEE_CNT], [HH_AIDE_VLNTR_CNT], [PRSNEL_OTHR_CNT], [NRS_AIDE_CNTRCT_CNT], [NRS_AIDE_FLTM_CNT]
		, [NRS_AIDE_PRTM_CNT], [CNSLR_EMPLEE_CNT], [CNSLR_VLNTR_CNT], [CRNA_CNT], [DNTST_CNTRCT_CNT], [DNTST_FLTM_CNT], [DNTST_PRTM_CNT], [DIETN_CNT], [DIETN_CNTRCT_CNT], [DIETN_FLTM_CNT], [DIETN_PRTM_CNT]
		, [DRCT_CARE_PRSNEL_CNT], [FOOD_SRVC_CNTRCT_CNT], [FOOD_SRVC_FLTM_CNT], [FOOD_SRVC_PRTM_CNT], [HH_AIDE_CNT], [HMMKR_EMPLEE_CNT], [HMMKR_VLNTR_CNT], [HSEKPNG_CNTRCT_CNT], [HSEKPNG_FLTM_CNT], [HSEKPNG_PRTM_CNT]
		, [LAB_TCHNCN_CNT], [LPN_CNT], [LPN_LVN_CNT], [LPN_LVN_CNTRCT_CNT], [LPN_LVN_FLTM_CNT], [LPN_LVN_PRTM_CNT], [LPN_LVN_VLNTR_CNT], [MDCL_DRCTR_CNTRCT_CNT], [MDCL_DRCTR_FLTM_CNT], [MDCL_DRCTR_PRTM_CNT]
		, [MDCL_SCL_WORKR_CNT], [MDCL_SCL_WORKR_VLNTR_CNT], [MDCL_TCHNLGST_CNT], [MDCTN_AIDE_CNTRCT_CNT], [MDCTN_AIDE_FLTM_CNT], [MDCTN_AIDE_PRTM_CNT], [MENTL_HLTH_SRVC_CNTRCT_CNT], [MENTL_HLTH_SRVC_FLTM_CNT]
		, [MENTL_HLTH_SRVC_PRTM_CNT], [NUCLR_MDCN_TCHNCN_CNT], [NAT_CNTRCT_CNT], [NAT_FLTM_CNT], [NAT_PRTM_CNT], [NRS_PRCTNR_CNT], [NRS_ADMINV_CNTRCT_CNT], [NRS_ADMINV_FLTM_CNT], [NRS_ADMINV_PRTM_CNT], [OCPTNL_THRPST_CNT]
		, [OCPTNL_THRPST_CNTRCT_CNT], [OCPTNL_THRPST_FLTM_CNT], [OCPTNL_THRPST_PRTM_CNT], [OT_AIDE_CNTRCT_CNT], [OT_AIDE_FLTM_CNT], [OT_AIDE_PRTM_CNT], [OT_ASTNT_CNTRCT_CNT], [OT_ASTNT_FLTM_CNT], [OT_ASTNT_PRTM_CNT]
		, [VLNTR_OTHR_CNT], [ACTVTY_STF_OTHR_CNTRCT_CNT], [ACTVTY_STF_OTHR_FLTM_CNT], [ACTVTY_STF_OTHR_PRTM_CNT], [PHYSN_OTHR_CNTRCT_CNT], [PHYSN_OTHR_FLTM_CNT], [PHYSN_OTHR_PRTM_CNT], [SCL_SRVC_OTHR_STF_CNTRCT_CNT]
		, [SCL_SRVC_OTHR_STF_FLTM_CNT], [SCL_SRVC_OTHR_STF_PRTM_CNT], [STF_OTHR_CNTRCT_CNT], [STF_OTHR_FLTM_CNT], [STF_OTHR_PRTM_CNT], [PHRMCST_CNTRCT_CNT], [PHRMCST_FLTM_CNT], [PHRMCST_PRTM_CNT], [PHYS_THRPST_CNTRCT_CNT]
		, [PHYS_THRPST_FLTM_CNT], [PHYS_THRPST_PRTM_CNT], [PHYSN_CNT], [PHYSN_VLNTR_CNT], [PHYSN_ASTNT_CNT], [PHYSN_EXT_CNTRCT_CNT], [PHYSN_EXT_FLTM_CNT], [PHYSN_EXT_PRTM_CNT], [RSDNT_PHYSN_CNT], [PDTRST_CNTRCT_CNT]
		, [PDTRST_FLTM_CNT], [PDTRST_PRTM_CNT], [PSYCHLGST_CNT], [PHYS_THRPST_STF_CNT], [PHYS_THRPST_CNT], [PHYS_THRPST_ARNGMT_CNT], [PT_AIDE_CNTRCT_CNT], [PT_AIDE_FLTM_CNT], [PT_AIDE_PRTM_CNT], [PT_ASTNT_CNTRCT_CNT]
		, [PT_ASTNT_FLTM_CNT], [PT_ASTNT_PRTM_CNT], [ACTVTY_PROFNL_CNTRCT_CNT], [ACTVTY_PROFNL_FLTM_CNT], [ACTVTY_PROFNL_PRTM_CNT], [RDLGY_TCHNCN_CNT], [REG_PHRMCST_CNT], [INHLTN_THRPST_CNT], [RN_CNT], [RN_CNTRCT_CNT]
		, [RN_FLTM_CNT], [RN_PRTM_CNT], [RN_VLNTR_CNT], [RN_DRCTR_CNTRCT_CNT], [RN_DRCTR_FLTM_CNT], [RN_DRCTR_PRTM_CNT], [SCL_WORKR_CNT], [SCL_WORKR_CNTRCT_CNT], [SCL_WORKR_FLTM_CNT], [SCL_WORKR_PRTM_CNT]
		, [SPCH_PTHLGST_ARNGMT_CNT], [SPCH_PTHLGST_CNTRCT_CNT], [SPCH_PTHLGST_FLTM_CNT], [SPCH_PTHLGST_PRTM_CNT], [SPCH_PTHLGST_CNT], [SPCH_PTHLGST_AUDLGST_CNT], [TCHNCL_STF_NUM], [TCHNCN_CNT], [THRPTC_RCRTNL_CNTRCT_CNT]
		, [THRPTC_RCRTNL_FLTM_CNT], [THRPTC_RCRTNL_PRTM_CNT], [EMPLEE_CNT], [VLNTR_CNT], [SBUNIT_CNT], [SBUNIT_SW], [SBUNIT_OPRTN_SW], [DNTL_SRGRY_SW], [OTLRYNGLGY_SRGRY_SW], [ENDSCPY_SRGRY_SW], [OB_GYN_SRGRY_SW]
		, [OPTHMLGY_SRGRY_SW], [ORTHPDC_SRGRY_SW], [OTHR_SRGRY_SW], [PAIN_SRGRY_SW], [PLSTC_SRGRY_SW], [FT_SRGRY_SW], [SB_SW], [SB_SIZE_CD], [TCHNLGST_2_YR_RDLGC_CNT], [TCHNLGST_ASCT_DGR_CNT], [TCHNLGST_BS_BA_DGR_CNT]
		, [DLYS_STN_CNT]'   + ')' +

		'SELECT		[CreatedDate], [CreatedBy], [LastUpdated], [LastUpdatedBy], [SrcFileName], [ACTIVE], [EffectiveDate], [ExpirationDate], [lstCNNKey], [PRVDR_CTGRY_SBTYP_CD], [PRVDR_CTGRY_CD]
		, [CHOW_CNT], [CHOW_DT], [CITY_NAME], [ACPTBL_POC_SW], [CMPLNC_STUS_CD], [SSA_CNTY_CD], [CROSS_REF_PROVIDER_NUMBER], [CRTFCTN_DT], [ELGBLTY_SW], [FAC_NAME], [INTRMDRY_CARR_CD]
		, [MDCD_VNDR_NUM], [ORGNL_PRTCPTN_DT], [CHOW_PRIOR_DT], [INTRMDRY_CARR_PRIOR_CD], [PRVDR_NUM], [RGN_CD], [SKLTN_REC_SW], [STATE_CD], [SSA_STATE_CD], [STATE_RGN_CD], [ST_ADR], [PHNE_NUM]
		, [PGM_TRMNTN_CD], [TRMNTN_EXPRTN_DT], [CRTFCTN_ACTN_TYPE_CD], [GNRL_CNTL_TYPE_CD], [ZIP_CD], [FIPS_STATE_CD], [FIPS_CNTY_CD], [CBSA_URBN_RRL_IND], [CBSA_CD], [ACRDTN_EFCTV_DT], [ACRDTN_EXPRTN_DT]
		, [ACRDTN_TYPE_CD], [TOT_AFLTD_AMBLNC_SRVC_CNT], [TOT_AFLTD_ASC_CNT], [TOT_COLCTD_HOSP_CNT], [TOT_AFLTD_ESRD_CNT], [TOT_AFLTD_FQHC_CNT], [TOT_AFLTD_HHA_CNT], [TOT_AFLTD_HOSPC_CNT], [TOT_AFLTD_OPO_CNT]
		, [TOT_AFLTD_PRTF_CNT], [TOT_AFLTD_RHC_CNT], [TOT_AFLTD_SNF_CNT], [AFLTD_PRVDR_CNT], [RSDNT_PGM_ALPTHC_SW], [RSDNT_PGM_DNTL_SW], [RSDNT_PGM_OSTPTHC_SW], [RSDNT_PGM_OTHR_SW], [RSDNT_PGM_PDTRC_SW]
		, [LAB_SRVC_CD], [PHRMCY_SRVC_CD], [RDLGY_SRVC_CD], [ASC_BGN_SRVC_DT], [FREESTNDNG_ASC_SW], [OVRRD_BED_CNT_SW], [CRTFD_BED_CNT], [ICFIID_BED_CNT], [MDCD_NF_BED_CNT], [MDCR_SNF_BED_CNT]
		, [MDCR_MDCD_SNF_BED_CNT], [AIDS_BED_CNT], [ALZHMR_BED_CNT], [DLYS_BED_CNT], [DSBL_CHLDRN_BED_CNT], [HEAD_TRMA_BED_CNT], [HOSPC_BED_CNT], [HNTGTN_DEASE_BED_CNT], [REHAB_BED_CNT], [VNTLTR_BED_CNT]
		, [BED_CNT], [BRNCH_CNT], [BRNCH_OPRTN_SW], [CAH_PSYCH_DPU_SW], [CAH_REHAB_DPU_SW], [CAH_SB_SW], [CRDC_CTHRTZTN_PRCDR_ROOMS_CNT], [GNRL_FAC_TYPE_CD], [CHOW_SW], [CLIA_ID_NUMBER_1], [CLIA_ID_NUMBER_2]
		, [CLIA_ID_NUMBER_3], [CLIA_ID_NUMBER_4], [CLIA_ID_NUMBER_5], [COLCTN_STUS_SW], [RN_24_HR_WVR_SW], [RN_7_DAY_WVR_SW], [BED_PER_ROOM_WVR_SW], [LSC_WVR_SW], [ROOM_SIZE_WVR_SW], [ENDSCPY_PRCDR_ROOMS_CNT]
		, [ESRD_NTWRK_NUM], [EXPRMT_RSRCH_CNDCTD_SW], [FAX_PHNE_NUM], [FY_END_MO_DAY_CD], [FQHC_APPROVED_RHC_PROVIDER_NUM], [FED_FUNDD_FQHC_SW], [HHA_QLFYD_OPT_SPCH_SW], [HH_AIDE_TRNG_PGM_CD]
		, [HOME_TRNG_SPRT_ONLY_SRVC_SW], [MDCR_HOSPC_SW], [HOSP_BSD_SW], [INCNTR_NCTRNL_SRVC_SW], [LTC_CROSS_REF_PROVIDER_NUMBER], [MDCL_SCHL_AFLTN_CD], [MEDICARE_HOSPICE_PROVIDER_NUM], [MDCD_MDCR_PRTCPTG_PRVDR_SW]
		, [MEDICARE_MEDICAID_PRVDR_NUMBER], [MLT_FAC_ORG_NAME], [MLT_OWND_FAC_ORG_SW], [NCRY_PRVDR_DSGNTD_DT], [NCRY_PRVDR_DSGNTD_AS_SW], [NCRY_PRVDR_LOST_DT], [MEET_1861_SW], [NPP_TYPE_CD], [TOT_OFSITE_CNCR_HOSP_CNT]
		, [TOT_OFSITE_CHLDRN_HOSP_CNT], [TOT_OFSITE_EMER_DEPT_CNT], [TOT_OFSITE_INPTNT_LCTN_CNT], [TOT_OFSITE_LTC_HOSP_CNT], [TOT_OFSITE_OPTHLMC_SRGRY_CNT], [TOT_OFSITE_OTHR_LCTN_CNT], [TOT_OFSITE_PSYCH_HOSP_CNT]
		, [TOT_OFSITE_PSYCH_UNIT_CNT], [TOT_OFSITE_REHAB_HOSP_CNT], [TOT_OFSITE_REHAB_UNIT_CNT], [TOT_OFSITE_URGNT_CARE_CNTR_CNT], [OFSITE_LCTN_CNT], [OPRTG_ROOM_CNT], [ORGNZ_FMLY_MBR_GRP_SW], [ORGNZ_RSDNT_GRP_SW]
		, [PARENT_PROVIDER_NUMBER], [FQHC_APRVD_RHC_SW], [MDCR_PRTCPTN_OP_PT_SPCH_SW], [PGM_PRTCPTN_CD], [PRVDR_BSD_FAC_SW], [PRVNC_CD], [PSYCH_UNIT_BED_CNT], [PSYCH_UNIT_EFCTV_DT], [PSYCH_UNIT_SW], [PSYCH_UNIT_TRMNTN_CD]
		, [PSYCH_UNIT_TRMNTN_DT], [REHAB_UNIT_BED_CNT], [REHAB_UNIT_EFCTV_DT], [REHAB_UNIT_SW], [REHAB_UNIT_TRMNTN_CD], [REHAB_UNIT_TRMNTN_DT], [RELATED_PROVIDER_NUMBER], [ACUTE_RNL_DLYS_SRVC_CD], [PSYCH_SRVC_CD]
		, [HH_AIDE_SRVC_CD], [ALCHL_DRUG_SRVC_CD], [ANSTHSA_SRVC_CD], [APLNC_EQUIP_SRVC_CD], [AUDLGY_SRVC_CD], [BLOOD_SRVC_OFSITE_RSDNT_SW], [BLOOD_SRVC_ONST_NRSDNT_SW], [BLOOD_SRVC_ONST_RSDNT_SW]
		, [BURN_CARE_UNIT_SRVC_CD], [CRDC_CTHRTZTN_LAB_SRVC_CD], [OPEN_HRT_SRGRY_SRVC_CD], [CARF_IP_REHAB_SRVC_CD], [CHMTHRPY_SRVC_CD], [CHRPRCTIC_SRVC_CD], [CL_SRVC_OFSITE_RSDNT_SW], [CL_SRVC_ONST_NRSDNT_SW]
		, [CL_SRVC_ONST_RSDNT_SW], [CL_SRVC_CD], [CRNRY_CARE_UNIT_SRVC_CD], [CNSLNG_SRVC_CD], [CT_SCAN_SRVC_CD], [DNTL_SRVC_CD], [DNTL_SRVC_OFSITE_RSDNT_SW], [DNTL_SRVC_ONST_NRSDNT_SW], [DNTL_SRVC_ONST_RSDNT_SW]
		, [SHCK_TRMA_SRVC_CD], [DGNSTC_RDLGY_SRVC_CD], [DTRY_SRVC_CD], [DTRY_OFSITE_RSDNT_SW], [DTRY_ONST_NRSDNT_SW], [DTRY_ONST_RSDNT_SW], [DCTD_ER_SRVC_CD], [EMER_PSYCH_SRVC_CD], [XTRCRPRL_SHCK_LTHTRPTR_SRVC_CD]
		, [FRNSC_PSYCH_SRVC_CD], [GRTRC_PSYCH_SRVC_CD], [GRNTLGCL_SPCLTY_SRVC_CD], [SP_HOME_TRNG_SPRT_HD_SW], [HMDLYS_SRVC_SW], [HMMKR_SRVC_CD], [HSEKPNG_SRVC_OFSITE_RSDNT_SW], [HSEKPNG_SRVC_ONST_NRSDNT_SW]
		, [HSEKPNG_SRVC_ONST_RSDNT_SW], [IP_SRGCL_SRVC_CD], [INTRN_RSDNT_SRVC_CD], [MDCL_SCL_SRVC_CD], [MDCL_SUPLY_SRVC_CD], [ICU_SRVC_CD], [MDCR_TRNSPLNT_CNTR_SRVC_CD], [MENTL_HLTH_OFSITE_RSDNT_SW]
		, [MENTL_HLTH_ONST_NRSDNT_SW], [MENTL_HLTH_ONST_RSDNT_SW], [MGNTC_RSNC_IMG_SRVC_CD], [NEONTL_ICU_SRVC_CD], [NEONTL_NRSRY_SRVC_CD], [NRSRGCL_SRVC_CD], [ORGN_TRNSPLNT_SRVC_CD], [NUCLR_MDCN_SRVC_CD]
		, [NRSNG_SRVC_EMPLEE_SW], [NRSNG_SRVC_CNTRCTR_SW], [NRSNG_SRVC_ARNGMT_SW], [NRSNG_SRVC_CD], [NRSNG_SRVC_OFSITE_RSDNT_SW], [NRSNG_SRVC_ONST_NRSDNT_SW], [NRSNG_SRVC_ONST_RSDNT_SW], [NTRTNL_GDNC_SRVC_CD]
		, [OB_SRVC_CD], [OPTHLMC_SRGY_SRVC_CD], [OPTMTRC_SRVC_CD], [OPRTG_ROOM_SRVC_CD], [ORTHPDC_SRGY_SRVC_CD], [ORTHTC_PRSTHTC_EMPLEE_SW], [ORTHTC_PRSTHTC_CNTRCTR_SW], [ORTHTC_PRSTHTC_ARNGMT_SW], [OT_EMPLEE_SW]
		, [OT_CNTRCTR_SW], [OT_ARNGMT_SW], [OT_SRVC_CD], [OT_SRVC_OFSITE_RSDNT_SW], [OT_SRVC_ONST_NRSDNT_SW], [OT_SRVC_ONST_RSDNT_SW], [OTHR_SRVC_CD], [OP_SRVC_CD], [OP_PSYCH_SRVC_CD], [OP_REHAB_SRVC_CD]
		, [OP_SRGRY_UNIT_SRVC_CD], [PED_SRVC_CD], [PED_ICU_SRVC_CD], [SP_HOME_TRNG_SPRT_PD_SW], [PRTNL_DLYS_SRVC_SW], [PET_SCAN_SRVC_CD], [PHRMCY_SRVC_OFSITE_RSDNT_SW], [PHRMCY_SRVC_ONST_NRSDNT_SW]
		, [PHRMCY_SRVC_ONST_RSDNT_SW], [PHYSN_EMPLEE_SW], [PHYSN_CNTRCTR_SW], [PHYSN_ARNGMT_SW], [PHYSN_SRVC_CD], [PHYSN_EXT_SRVC_OFSITE_RSDNT_SW], [PHYSN_EXT_SRVC_ONST_NRSDNT_SW], [PHYSN_EXT_SRVC_ONST_RSDNT_SW]
		, [PHYSN_SRVC_OFSITE_RSDNT_SW], [PHYSN_SRVC_ONST_NRSDNT_SW], [PHYSN_SRVC_ONST_RSDNT_SW], [PDTRY_SRVC_OFSITE_RSDNT_SW], [PDTRY_SRVC_ONST_NRSDNT_SW], [PDTRY_SRVC_ONST_RSDNT_SW], [PSTOPRTV_RCVRY_SRVC_CD]
		, [CHLD_ADLSCNT_PSYCH_SRVC_CD], [PSYCHLGCL_EMPLEE_SW], [PSYCHLGCL_CNTRCTR_SW], [PSYCHLGCL_ARNGMT_SW], [PT_EMPLEE_SW], [PT_CNTRCTR_SW], [PT_ARNGMT_SW], [PT_SRVC_CD], [PT_OFSITE_RSDNT_SW], [PT_ONST_NRSDNT_SW]
		, [PT_ONST_RSDNT_SW], [RCNSTRCTN_SRGY_SRVC_CD], [RSPRTRY_CARE_EMPLEE_SW], [RSPRTRY_CARE_CNTRCTR_SW], [RSPRTRY_CARE_ARNGMT_SW], [RSPRTRY_CARE_SRVC_CD], [SHRT_TERM_IP_SRVC_CD], [SCL_EMPLEE_SW], [SCL_CNTRCTR_SW]
		, [SCL_ARNGMT_SW], [SCL_SRVC_CD], [SCL_WORK_SRVC_OFSITE_RSDNT_SW], [SCL_WORK_SRVC_ONST_NRSDNT_SW], [SCL_WORK_SRVC_ONST_RSDNT_SW], [SPCH_PTHLGY_EMPLEE_SW], [SPCH_PTHLGY_CNTRCTR_SW], [SPCH_PTHLGY_ARNGMT_SW]
		, [SPCH_PTHLGY_SRVC_CD], [SPCH_PTHLGY_OFSITE_RSDNT_SW], [SPCH_PTHLGY_ONST_NRSDNT_SW], [SPCH_PTHLGY_ONST_RSDNT_SW], [SPCH_THRPY_SRVC_CD], [SRGCL_ICU_SRVC_CD], [ACTVTY_OTHR_OFSITE_RSDNT_SW]
		, [ACTVTY_OTHR_ONST_NRSDNT_SW], [ACTVTY_OTHR_ONST_RSDNT_SW], [SCL_SRVC_OTHR_OFSITE_RSDNT_SW], [SCL_SRVC_OTHR_ONST_NRSDNT_SW], [SCL_SRVC_OTHR_ONST_RSDNT_SW], [ACTVTY_OFSITE_RSDNT_SW], [ACTVTY_ONST_NRSDNT_SW]
		, [ACTVTY_ONST_RSDNT_SW], [THRPTC_RDLGY_SRVC_CD], [THRPTC_RCRTNL_OFSITE_RSDNT_SW], [THRPTC_RCRTNL_ONST_NRSDNT_SW], [THRPTC_RCRTNL_ONST_RSDNT_SW], [URGNT_CARE_SRVC_CD], [VCTNL_GDNC_SRVC_CD]
		, [VCTNL_SRVC_OFSITE_RSDNT_SW], [VCTNL_SRVC_ONST_NRSDNT_SW], [VCTNL_SRVC_ONST_RSDNT_SW], [DGNSTC_XRAY_OFSITE_RSDNT_SW], [DGNSTC_XRAY_ONST_NRSDNT_SW], [DGNSTC_XRAY_ONST_RSDNT_SW], [ACUTE_RESP_CARE_CD]
		, [OVRRD_STFG_SW], [PROFNL_ADMIN_CNTRCT_CNT], [PROFNL_ADMIN_FLTM_CNT], [PROFNL_ADMIN_PRTM_CNT], [HH_AIDE_EMPLEE_CNT], [HH_AIDE_VLNTR_CNT], [PRSNEL_OTHR_CNT], [NRS_AIDE_CNTRCT_CNT], [NRS_AIDE_FLTM_CNT]
		, [NRS_AIDE_PRTM_CNT], [CNSLR_EMPLEE_CNT], [CNSLR_VLNTR_CNT], [CRNA_CNT], [DNTST_CNTRCT_CNT], [DNTST_FLTM_CNT], [DNTST_PRTM_CNT], [DIETN_CNT], [DIETN_CNTRCT_CNT], [DIETN_FLTM_CNT], [DIETN_PRTM_CNT]
		, [DRCT_CARE_PRSNEL_CNT], [FOOD_SRVC_CNTRCT_CNT], [FOOD_SRVC_FLTM_CNT], [FOOD_SRVC_PRTM_CNT], [HH_AIDE_CNT], [HMMKR_EMPLEE_CNT], [HMMKR_VLNTR_CNT], [HSEKPNG_CNTRCT_CNT], [HSEKPNG_FLTM_CNT], [HSEKPNG_PRTM_CNT]
		, [LAB_TCHNCN_CNT], [LPN_CNT], [LPN_LVN_CNT], [LPN_LVN_CNTRCT_CNT], [LPN_LVN_FLTM_CNT], [LPN_LVN_PRTM_CNT], [LPN_LVN_VLNTR_CNT], [MDCL_DRCTR_CNTRCT_CNT], [MDCL_DRCTR_FLTM_CNT], [MDCL_DRCTR_PRTM_CNT]
		, [MDCL_SCL_WORKR_CNT], [MDCL_SCL_WORKR_VLNTR_CNT], [MDCL_TCHNLGST_CNT], [MDCTN_AIDE_CNTRCT_CNT], [MDCTN_AIDE_FLTM_CNT], [MDCTN_AIDE_PRTM_CNT], [MENTL_HLTH_SRVC_CNTRCT_CNT], [MENTL_HLTH_SRVC_FLTM_CNT]
		, [MENTL_HLTH_SRVC_PRTM_CNT], [NUCLR_MDCN_TCHNCN_CNT], [NAT_CNTRCT_CNT], [NAT_FLTM_CNT], [NAT_PRTM_CNT], [NRS_PRCTNR_CNT], [NRS_ADMINV_CNTRCT_CNT], [NRS_ADMINV_FLTM_CNT], [NRS_ADMINV_PRTM_CNT], [OCPTNL_THRPST_CNT]
		, [OCPTNL_THRPST_CNTRCT_CNT], [OCPTNL_THRPST_FLTM_CNT], [OCPTNL_THRPST_PRTM_CNT], [OT_AIDE_CNTRCT_CNT], [OT_AIDE_FLTM_CNT], [OT_AIDE_PRTM_CNT], [OT_ASTNT_CNTRCT_CNT], [OT_ASTNT_FLTM_CNT], [OT_ASTNT_PRTM_CNT]
		, [VLNTR_OTHR_CNT], [ACTVTY_STF_OTHR_CNTRCT_CNT], [ACTVTY_STF_OTHR_FLTM_CNT], [ACTVTY_STF_OTHR_PRTM_CNT], [PHYSN_OTHR_CNTRCT_CNT], [PHYSN_OTHR_FLTM_CNT], [PHYSN_OTHR_PRTM_CNT], [SCL_SRVC_OTHR_STF_CNTRCT_CNT]
		, [SCL_SRVC_OTHR_STF_FLTM_CNT], [SCL_SRVC_OTHR_STF_PRTM_CNT], [STF_OTHR_CNTRCT_CNT], [STF_OTHR_FLTM_CNT], [STF_OTHR_PRTM_CNT], [PHRMCST_CNTRCT_CNT], [PHRMCST_FLTM_CNT], [PHRMCST_PRTM_CNT], [PHYS_THRPST_CNTRCT_CNT]
		, [PHYS_THRPST_FLTM_CNT], [PHYS_THRPST_PRTM_CNT], [PHYSN_CNT], [PHYSN_VLNTR_CNT], [PHYSN_ASTNT_CNT], [PHYSN_EXT_CNTRCT_CNT], [PHYSN_EXT_FLTM_CNT], [PHYSN_EXT_PRTM_CNT], [RSDNT_PHYSN_CNT], [PDTRST_CNTRCT_CNT]
		, [PDTRST_FLTM_CNT], [PDTRST_PRTM_CNT], [PSYCHLGST_CNT], [PHYS_THRPST_STF_CNT], [PHYS_THRPST_CNT], [PHYS_THRPST_ARNGMT_CNT], [PT_AIDE_CNTRCT_CNT], [PT_AIDE_FLTM_CNT], [PT_AIDE_PRTM_CNT], [PT_ASTNT_CNTRCT_CNT]
		, [PT_ASTNT_FLTM_CNT], [PT_ASTNT_PRTM_CNT], [ACTVTY_PROFNL_CNTRCT_CNT], [ACTVTY_PROFNL_FLTM_CNT], [ACTVTY_PROFNL_PRTM_CNT], [RDLGY_TCHNCN_CNT], [REG_PHRMCST_CNT], [INHLTN_THRPST_CNT], [RN_CNT], [RN_CNTRCT_CNT]
		, [RN_FLTM_CNT], [RN_PRTM_CNT], [RN_VLNTR_CNT], [RN_DRCTR_CNTRCT_CNT], [RN_DRCTR_FLTM_CNT], [RN_DRCTR_PRTM_CNT], [SCL_WORKR_CNT], [SCL_WORKR_CNTRCT_CNT], [SCL_WORKR_FLTM_CNT], [SCL_WORKR_PRTM_CNT]
		, [SPCH_PTHLGST_ARNGMT_CNT], [SPCH_PTHLGST_CNTRCT_CNT], [SPCH_PTHLGST_FLTM_CNT], [SPCH_PTHLGST_PRTM_CNT], [SPCH_PTHLGST_CNT], [SPCH_PTHLGST_AUDLGST_CNT], [TCHNCL_STF_NUM], [TCHNCN_CNT], [THRPTC_RCRTNL_CNTRCT_CNT]
		, [THRPTC_RCRTNL_FLTM_CNT], [THRPTC_RCRTNL_PRTM_CNT], [EMPLEE_CNT], [VLNTR_CNT], [SBUNIT_CNT], [SBUNIT_SW], [SBUNIT_OPRTN_SW], [DNTL_SRGRY_SW], [OTLRYNGLGY_SRGRY_SW], [ENDSCPY_SRGRY_SW], [OB_GYN_SRGRY_SW]
		, [OPTHMLGY_SRGRY_SW], [ORTHPDC_SRGRY_SW], [OTHR_SRGRY_SW], [PAIN_SRGRY_SW], [PLSTC_SRGRY_SW], [FT_SRGRY_SW], [SB_SW], [SB_SIZE_CD], [TCHNLGST_2_YR_RDLGC_CNT], [TCHNLGST_ASCT_DGR_CNT], [TCHNLGST_BS_BA_DGR_CNT]
		, [DLYS_STN_CNT]	'
				+
		' FROM		[AceMasterData].[lst].[LIST_CCN]'
				+
		'SET IDENTITY_INSERT ' + @ConnectionString + ' OFF '

		--PRINT @SqlString
		EXECUTE sp_executesql @SqlString

END

	
	--Master -DONT TOUCH
	--SELECT * FROM [lst].[List_CCN]
	--Targets
	/*
	--	SELECT * FROM ACDW_CLMS_SHCN_MSSP.[lst].[List_CCN]
	--	SELECT * FROM ACDW_CLMS_UHC.[lst].[List_CCN]
	--	SELECT * FROM ACDW_CLMS_WLC.[lst].[List_CCN]
	--	SELECT * FROM ACECAREDW_TEST.[lst].[List_CCN]
		SELECT * FROM ACECAREDW.[lst].[List_CCN]
		SELECT * FROM DEV_ACECAREDW.[lst].[List_CCN]
		SELECT * FROM ACDW_CLMS_DHTX.[lst].[List_CCN]
		SELECT * FROM ACDW_CLMS_CIGNA_MA.[lst].[List_CCN]
		SELECT * FROM ACDW_CLMS_SHCN_BCBS.[lst].[List_CCN]
		SELECT * FROM ACDW_CLMS_AET_TX_COM.[lst].[List_CCN]
		SELECT * FROM ACDW_CLMS_AET_MA.[lst].[List_CCN]
	*/
	
	
	
