CREATE TABLE [lst].[z_List_DRUG_PRODUCT] (
    [CreatedDate]               DATETIME       DEFAULT (getdate()) NOT NULL,
    [CreatedBy]                 VARCHAR (50)   DEFAULT (suser_sname()) NOT NULL,
    [LastUpdated]               DATETIME       DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]             VARCHAR (50)   DEFAULT (suser_sname()) NOT NULL,
    [SrcFileName]               VARCHAR (50)   NULL,
    [lstDrugProductKey]         INT            IDENTITY (1, 1) NOT NULL,
    [PRODUCTID]                 VARCHAR (50)   NULL,
    [PRODUCTNDC]                VARCHAR (15)   NULL,
    [PRODUCTTYPENAME]           VARCHAR (50)   NULL,
    [PROPRIETARYNAME]           VARCHAR (2500) NULL,
    [PROPRIETARYNAMESUFFIX]     VARCHAR (250)  NULL,
    [NONPROPRIETARYNAME]        VARCHAR (1000) NULL,
    [DOSAGEFORMNAME]            VARCHAR (50)   NULL,
    [ROUTENAME]                 VARCHAR (500)  NULL,
    [STARTMARKETINGDATE]        VARCHAR (10)   NULL,
    [ENDMARKETINGDATE]          VARCHAR (10)   NULL,
    [MARKETINGCATEGORYNAME]     VARCHAR (50)   NULL,
    [APPLICATIONNUMBER]         VARCHAR (20)   NULL,
    [LABELERNAME]               VARCHAR (400)  NULL,
    [SUBSTANCENAME]             VARCHAR (5000) NULL,
    [ACTIVE_NUMERATOR_STRENGTH] VARCHAR (5000) NULL,
    [ACTIVE_INGRED_UNIT]        VARCHAR (5000) NULL,
    [PHARM_CLASSES]             VARCHAR (5000) NULL,
    [DEASCHEDULE]               VARCHAR (10)   NULL,
    [ACTIVE]                    CHAR (1)       DEFAULT ('Y') NULL,
    [EffectiveDate]             DATE           DEFAULT (getdate()) NULL,
    [ExpirationDate]            DATE           DEFAULT ('2099-12-31') NULL,
    PRIMARY KEY CLUSTERED ([lstDrugProductKey] ASC)
);

