CREATE TABLE [dbo].[ATHENAEMR] (
    [QM_DESC]        VARCHAR (500) NULL,
    [QM]             VARCHAR (100) NULL,
    [AHR_QM_DESC]    VARCHAR (500) NULL,
    [ACTIVE]         CHAR (1)      NULL,
    [EFFECTIVEDATE]  VARCHAR (50)  NULL,
    [EXPIRATIONDATE] VARCHAR (50)  NULL,
    [Column 6]       VARCHAR (50)  NULL
);

