CREATE TABLE [dbo].[LIST_ZIPCODES_COUNTIES] (
    [ZIP_URN]   INT          IDENTITY (1, 1) NOT NULL,
    [CLIENT_ID] VARCHAR (5)  NOT NULL,
    [ZIP_CODE]  VARCHAR (15) NULL,
    [POD_NAME]  VARCHAR (50) NULL,
    [POD]       VARCHAR (5)  NULL,
    PRIMARY KEY CLUSTERED ([ZIP_URN] ASC)
);

